name: Terraform Azure VM

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .  # run in repo root

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (Service Principal + Secret)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - run: terraform init
      - run: terraform fmt -check
      - run: terraform validate

      - name: Terraform Plan (PRs)
        if: github.event_name == 'pull_request'
        run: terraform plan -input=false \
             -var "admin_ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"

      - name: Terraform Apply (main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false \
             -var "admin_ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
