name: Terraform Azure VM

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - uses: actions/checkout@v4

      # Azure login using a single JSON secret (AZURE_CREDENTIALS)
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      # PLAN on PRs. Treat exit code 2 ("changes present") as success.
      - name: Terraform Plan (PRs)
        if: github.event_name == 'pull_request'
        env:
          TF_VAR_admin_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        run: |
          set +e
          terraform plan -input=false -no-color -detailed-exitcode
          code=$?
          set -e
          # 0 = no changes, 2 = changes (OK), 1 = error (fail)
          if [ $code -eq 1 ]; then
            echo "Terraform plan failed"
            exit 1
          fi
          echo "Terraform plan exit code: $code (treating as success)"

      # APPLY on push to main
      - name: Terraform Apply (main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          TF_VAR_admin_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        run: terraform apply -auto-approve -input=false
