name: Terraform Azure VM

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .  # run in repo root

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - run: terraform init
      - run: terraform fmt -check
      - run: terraform validate

      - name: Terraform Plan (PRs)       
        if: github.event_name == 'pull_request'
        env:
          TF_VAR_admin_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        run: terraform plan -input=false

      - name: Terraform Apply (main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          TF_VAR_admin_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        run: terraform apply -auto-approve -input=false

        
